name: Kmp CI CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  kmp_build_check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Set up JDK 17"
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: "Set build env --> 3: Android SDK"
      uses: android-actions/setup-android@v3

    - name: "Set build env --> 3: Config gradle"
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current

    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew
      
    - name: "Build with Gradle"
      run: ./gradlew build
